source 'https://rubygems.org'

gem 'jekyll', '~> 4.0.1'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'sass'
gem 'octopress'
gem 'jekyll-sitemap'
gem 'guard-jekyll-plus'
gem 'jemoji'
gem 'rouge'
gem 'guard'
gem 'guard-livereload'
gem 'rack-livereload'
gem 'thin'
gem 'rubocop'
gem 'jekyll-feed'
