source 'https://rubygems.org'

gem 'jekyll', '~> 3.7.4'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'sass'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'jekyll-sitemap'
gem 'guard-jekyll-plus'
gem 'jemoji'
gem 'rouge'
gem 'guard'
gem 'guard-livereload'
gem 'rack-livereload'
gem 'thin'
gem 'rubocop'
gem 'jekyll-feed'
